name: Deploy usando SCP

on:
 workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Transferir somente o conteúdo da pasta
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USER }}
        password: ${{ secrets.HOSTINGER_PASSWORD}}
        port: 65002
        target: /home/u331460685/domains/app.thepurpose.com.br/public_html/
        source: *
